#!/bin/bash
# =============================================================================
# Comandos de Monitoreo en Tiempo Real - GuatePass
# =============================================================================
# Estos comandos deben ejecutarse en terminales separadas mientras 
# se ejecuta test-flujo-completo-mejorado.sh
# =============================================================================

# Configuración (ajustar si es necesario)
STACK_NAME="${1:-guatepass-stack}"
REGION="${AWS_REGION:-us-east-1}"
STAGE="dev"
PROJECT_NAME="guatepass"

# Obtener recursos del stack
STATE_MACHINE_ARN=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --query 'Stacks[0].Outputs[?OutputKey==`StateMachineArn`].OutputValue' \
    --output text 2>/dev/null)

STATE_MACHINE_NAME=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --query 'Stacks[0].Outputs[?OutputKey==`StateMachineName`].OutputValue' \
    --output text 2>/dev/null)

EVENT_BUS_NAME=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --query 'Stacks[0].Outputs[?OutputKey==`EventBusName`].OutputValue' \
    --output text 2>/dev/null)

SNS_TOPIC_ARN=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$REGION" \
    --query 'Stacks[0].Outputs[?OutputKey==`SnsTopicArn`].OutputValue' \
    --output text 2>/dev/null)

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  GuatePass - Comandos de Monitoreo en Tiempo Real            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "Stack: $STACK_NAME"
echo "Region: $REGION"
echo "Stage: $STAGE"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 EJECUTA ESTOS COMANDOS EN TERMINALES SEPARADAS:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Terminal 1: Step Functions - Ejecuciones en tiempo real
echo "🔵 TERMINAL 1: Step Functions - Ejecuciones en Tiempo Real"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "watch -n 2 'aws stepfunctions list-executions \\"
echo "  --state-machine-arn \"$STATE_MACHINE_ARN\" \\"
echo "  --region \"$REGION\" \\"
echo "  --max-results 5 \\"
echo "  --query \"executions[*].[executionArn,status,startDate]\" \\"
echo "  --output table'"
echo ""
echo "O para ver detalles de la última ejecución:"
echo "while true; do clear; echo \"=== Step Functions Executions ===\"; \\"
echo "  aws stepfunctions list-executions \\"
echo "    --state-machine-arn \"$STATE_MACHINE_ARN\" \\"
echo "    --region \"$REGION\" \\"
echo "    --max-results 10 \\"
echo "    --query \"executions[*].[status,startDate]\" \\"
echo "    --output table; \\"
echo "  sleep 3; done"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Terminal 2: CloudWatch Logs - Ingest Webhook
echo "🟢 TERMINAL 2: CloudWatch Logs - Ingest Webhook"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "aws logs tail /aws/lambda/${PROJECT_NAME}-ingest-webhook-${STAGE} \\"
echo "  --region \"$REGION\" \\"
echo "  --follow \\"
echo "  --format short"
echo ""
echo "O con filtro solo de eventos:"
echo "aws logs tail /aws/lambda/${PROJECT_NAME}-ingest-webhook-${STAGE} \\"
echo "  --region \"$REGION\" \\"
echo "  --follow \\"
echo "  --filter-pattern 'event_id' \\"
echo "  --format short"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Terminal 3: CloudWatch Logs - Validate Transaction
echo "🟡 TERMINAL 3: CloudWatch Logs - Validate Transaction"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "aws logs tail /aws/lambda/${PROJECT_NAME}-validate-transaction-${STAGE} \\"
echo "  --region \"$REGION\" \\"
echo "  --follow \\"
echo "  --format short"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Terminal 4: CloudWatch Logs - Update Tag Balance
echo "🟣 TERMINAL 4: CloudWatch Logs - Update Tag Balance"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "aws logs tail /aws/lambda/${PROJECT_NAME}-update-tag-balance-${STAGE} \\"
echo "  --region \"$REGION\" \\"
echo "  --follow \\"
echo "  --format short"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Terminal 5: CloudWatch Logs - Persist Transaction
echo "🔴 TERMINAL 5: CloudWatch Logs - Persist Transaction"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "aws logs tail /aws/lambda/${PROJECT_NAME}-persist-transaction-${STAGE} \\"
echo "  --region \"$REGION\" \\"
echo "  --follow \\"
echo "  --format short"
echo ""
echo "O verificar que ts = event_id:"
echo "aws logs tail /aws/lambda/${PROJECT_NAME}-persist-transaction-${STAGE} \\"
echo "  --region \"$REGION\" \\"
echo "  --follow \\"
echo "  --filter-pattern '{ $.event_id = * && $.event_id = $.ts }' \\"
echo "  --format short"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Terminal 6: DynamoDB - Transactions Table
echo "⚪ TERMINAL 6: DynamoDB - Transacciones en Tiempo Real"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "while true; do clear; echo \"=== Transactions Table (últimas 5) ===\"; \\"
echo "  aws dynamodb scan \\"
echo "    --table-name Transactions-${STAGE} \\"
echo "    --region \"$REGION\" \\"
echo "    --limit 5 \\"
echo "    --query \"Items[*].[placa.S, event_id.S, ts.S, status.S, amount.N]\" \\"
echo "    --output table | head -20; \\"
echo "  echo \"\"; echo \"Verificando que ts = event_id...\"; \\"
echo "  aws dynamodb scan \\"
echo "    --table-name Transactions-${STAGE} \\"
echo "    --region \"$REGION\" \\"
echo "    --projection-expression \"event_id, #ts\" \\"
echo "    --expression-attribute-names '{\"#ts\":\"ts\"}' \\"
echo "    --query \"Items[*].[event_id.S, #ts.S]\" \\"
echo "    --output table | head -20; \\"
echo "  sleep 5; done"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Terminal 7: DynamoDB - Tags Table (balance updates)
echo "🔵 TERMINAL 7: DynamoDB - Tags Table (Actualización de Balance)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "while true; do clear; echo \"=== Tags Table (Balance Updates) ===\"; \\"
echo "  aws dynamodb scan \\"
echo "    --table-name Tags-${STAGE} \\"
echo "    --region \"$REGION\" \\"
echo "    --query \"Items[*].[tag_id.S, placa.S, balance.N, debt.N, last_updated.S]\" \\"
echo "    --output table | head -30; \\"
echo "  sleep 5; done"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Terminal 8: DynamoDB - UsersVehicles Table (saldo_disponible)
echo "🟢 TERMINAL 8: DynamoDB - UsersVehicles (Saldo Disponible)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "while true; do clear; echo \"=== UsersVehicles (Saldo Disponible) ===\"; \\"
echo "  aws dynamodb scan \\"
echo "    --table-name UsersVehicles-${STAGE} \\"
echo "    --region \"$REGION\" \\"
echo "    --filter-expression \"attribute_exists(saldo_disponible) AND tiene_tag = :true\" \\"
echo "    --expression-attribute-values '{\":true\":{\"BOOL\":true}}' \\"
echo "    --query \"Items[*].[placa.S, tag_id.S, saldo_disponible.N, tiene_tag.BOOL]\" \\"
echo "    --output table | head -30; \\"
echo "  echo \"\"; echo \"Verificando sincronización Tags vs UsersVehicles...\"; \\"
echo "  sleep 5; done"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Terminal 9: EventBridge - Eventos publicados
echo "🟡 TERMINAL 9: EventBridge - Eventos Publicados"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Ver eventos recientes publicados"
echo "aws events list-rule-names-by-target \\"
echo "  --target-arn \"$STATE_MACHINE_ARN\" \\"
echo "  --region \"$REGION\" \\"
echo "  --output table"
echo ""
echo "# Ver eventos en el bus (últimos minutos)"
echo "while true; do clear; echo \"=== EventBridge Events (últimos 2 minutos) ===\"; \\"
echo "  START_TIME=\$(date -u -v-2M +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -d '2 minutes ago' +%Y-%m-%dT%H:%M:%SZ); \\"
echo "  aws events list-events \\"
echo "    --event-bus-name \"$EVENT_BUS_NAME\" \\"
echo "    --start-time \"\$START_TIME\" \\"
echo "    --region \"$REGION\" \\"
echo "    --query \"Events[*].[Time, Source, DetailType]\" \\"
echo "    --output table 2>/dev/null || echo \"No hay eventos recientes\"; \\"
echo "  sleep 5; done"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Terminal 10: SNS - Notificaciones
echo "🟣 TERMINAL 10: SNS - Notificaciones Publicadas"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Ver suscriptores del topic"
echo "aws sns list-subscriptions-by-topic \\"
echo "  --topic-arn \"$SNS_TOPIC_ARN\" \\"
echo "  --region \"$REGION\" \\"
echo "  --output table"
echo ""
echo "# Ver logs de SNS (si CloudWatch tiene logs habilitados)"
echo "# Nota: SNS no guarda logs por defecto, pero puedes ver métricas"
echo "aws cloudwatch get-metric-statistics \\"
echo "  --namespace AWS/SNS \\"
echo "  --metric-name NumberOfMessagesPublished \\"
echo "  --dimensions Name=TopicArn,Value=\"$SNS_TOPIC_ARN\" \\"
echo "  --start-time \$(date -u -v-10M +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -d '10 minutes ago' +%Y-%m-%dT%H:%M:%SZ) \\"
echo "  --end-time \$(date -u +%Y-%m-%dT%H:%M:%SZ) \\"
echo "  --period 60 \\"
echo "  --statistics Sum \\"
echo "  --region \"$REGION\" \\"
echo "  --output table"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Terminal 11: Verificación de colisiones (ts = event_id)
echo "🔴 TERMINAL 11: Verificación Anti-Colisiones (ts = event_id)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "while true; do clear; echo \"=== Verificando que ts = event_id ===\"; \\"
echo "  echo \"\"; \\"
echo "  TOTAL=\$(aws dynamodb scan \\"
echo "    --table-name Transactions-${STAGE} \\"
echo "    --region \"$REGION\" \\"
echo "    --select COUNT \\"
echo "    --query 'Count' \\"
echo "    --output text); \\"
echo "  echo \"Total de transacciones: \$TOTAL\"; \\"
echo "  echo \"\"; \\"
echo "  # Verificar que ts = event_id"; \\"
echo "  aws dynamodb scan \\"
echo "    --table-name Transactions-${STAGE} \\"
echo "    --region \"$REGION\" \\"
echo "    --projection-expression \"placa, event_id, #ts\" \\"
echo "    --expression-attribute-names '{\"#ts\":\"ts\"}' \\"
echo "    --query \"Items[*].{placa: placa.S, event_id: event_id.S, ts: #ts.S}\" \\"
echo "    --output json | jq -r '.[] | select(.ts != .event_id) | \"⚠️  Colisión: placa=\(.placa) event_id=\(.event_id) ts=\(.ts)\"' 2>/dev/null || echo \"✅ Todas las transacciones tienen ts = event_id\"; \\"
echo "  echo \"\"; \\"
echo "  sleep 5; done"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Terminal 12: Dashboard completo (resumen)
echo "⚪ TERMINAL 12: Dashboard Completo (Resumen General)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "while true; do clear; \\"
echo "  echo \"╔══════════════════════════════════════════════════════════════╗\"; \\"
echo "  echo \"║           GuatePass - Dashboard en Tiempo Real               ║\"; \\"
echo "  echo \"╚══════════════════════════════════════════════════════════════╝\"; \\"
echo "  echo \"\"; \\"
echo "  echo \"📊 STEP FUNCTIONS:\"; \\"
echo "  aws stepfunctions list-executions \\"
echo "    --state-machine-arn \"$STATE_MACHINE_ARN\" \\"
echo "    --region \"$REGION\" \\"
echo "    --max-results 3 \\"
echo "    --query \"executions[*].[status,startDate]\" \\"
echo "    --output table | head -10; \\"
echo "  echo \"\"; \\"
echo "  echo \"💾 TRANSACCIONES:\"; \\"
echo "  aws dynamodb scan \\"
echo "    --table-name Transactions-${STAGE} \\"
echo "    --region \"$REGION\" \\"
echo "    --select COUNT \\"
echo "    --query 'Count' \\"
echo "    --output text | xargs -I {} echo \"   Total: {}\"; \\"
echo "  echo \"\"; \\"
echo "  echo \"🏷️  TAGS:\"; \\"
echo "  aws dynamodb scan \\"
echo "    --table-name Tags-${STAGE} \\"
echo "    --region \"$REGION\" \\"
echo "    --select COUNT \\"
echo "    --query 'Count' \\"
echo "    --output text | xargs -I {} echo \"   Total: {}\"; \\"
echo "  echo \"\"; \\"
echo "  echo \"👥 USUARIOS:\"; \\"
echo "  aws dynamodb scan \\"
echo "    --table-name UsersVehicles-${STAGE} \\"
echo "    --region \"$REGION\" \\"
echo "    --select COUNT \\"
echo "    --query 'Count' \\"
echo "    --output text | xargs -I {} echo \"   Total: {}\"; \\"
echo "  echo \"\"; \\"
echo "  sleep 5; done"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Links útiles
echo "🔗 ENLACES ÚTILES EN AWS CONSOLE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step Functions:"
echo "  https://console.aws.amazon.com/states/home?region=${REGION}#/statemachines/view/${STATE_MACHINE_NAME}"
echo ""
echo "DynamoDB Tables:"
echo "  https://console.aws.amazon.com/dynamodbv2/home?region=${REGION}#tables"
echo ""
echo "CloudWatch Logs:"
echo "  https://console.aws.amazon.com/cloudwatch/home?region=${REGION}#logsV2:log-groups"
echo ""
echo "EventBridge:"
echo "  https://console.aws.amazon.com/events/home?region=${REGION}#/eventbus/${EVENT_BUS_NAME}"
echo ""
echo "SNS:"
echo "  https://console.aws.amazon.com/sns/v3/home?region=${REGION}#/topic/${SNS_TOPIC_ARN}"
echo ""
echo "API Gateway:"
echo "  https://console.aws.amazon.com/apigateway/home?region=${REGION}#/apis"
echo ""

