AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GuatePass – Sistema completo de cobro automatizado de peajes

Parameters:
  StageName:
    Type: String
    Default: dev
    Description: Nombre del stage a desplegar (dev|prod, etc.)
  ProjectName:
    Type: String
    Default: guatepass
    Description: Nombre del proyecto

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.12
    Environment:
      Variables:
        USERS_TABLE: !Ref UsersVehicles
        TAGS_TABLE: !Ref Tags
        TRANSACTIONS_TABLE: !Ref Transactions
        INVOICES_TABLE: !Ref Invoices
        TOLLS_CATALOG_TABLE: !Ref TollsCatalog
        EVENT_BUS_NAME: !Ref GuatePassBus
        SNS_TOPIC_ARN: !Ref NotificationsTopic
  Api:
    EndpointConfiguration: REGIONAL

Resources:

  #### API (definido; rutas se agregan en el siguiente paso) ####
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  #### EventBridge ####
  GuatePassBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub "guatepass-bus-${StageName}"

  TollDetectedRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref GuatePassBus
      EventPattern:
        source:
          - guatepass.toll
        detail-type:
          - Toll Transaction Event
      State: ENABLED
      Targets:
        - Arn: !GetAtt ProcessTollStateMachine.Arn
          Id: ProcessTollTarget
          RoleArn: !GetAtt EventBridgeStepFunctionsRole.Arn
          InputTransformer:
            InputPathsMap:
              detail: "$.detail"
            InputTemplate: "<detail>"

  #### Step Functions ####
  ProcessTollStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub "${ProjectName}-process-toll-${StageName}"
      Type: STANDARD
      Tracing:
        Enabled: true
      Definition:
        Comment: "ProcessToll - Orquesta el procesamiento de transacciones de peaje con lógica de decisión por tipo de usuario"
        StartAt: ValidateTransaction
        States:
          ValidateTransaction:
            Type: Task
            Resource: !GetAtt ValidateTransactionFunction.Arn
            Comment: "Valida peaje, determina tipo de usuario y valida tag"
            Next: DetermineUserType
            Catch:
              - ErrorEquals:
                  - States.ALL
                ResultPath: "$.error"
                Next: HandleError
          DetermineUserType:
            Type: Choice
            Comment: "Decide qué flujo seguir según el tipo de usuario"
            Choices:
              - Variable: "$.user_type"
                StringEquals: "tag"
                Next: ProcessTagUser
              - Variable: "$.user_type"
                StringEquals: "registrado"
                Next: ProcessRegisteredUser
              - Variable: "$.user_type"
                StringEquals: "no_registrado"
                Next: ProcessUnregisteredUser
            Default: ProcessUnregisteredUser
          ProcessTagUser:
            Type: Pass
            Comment: "Flujo para usuario con Tag (Caso C)"
            Result: "Procesando usuario con Tag"
            Next: CalculateCharge
          ProcessRegisteredUser:
            Type: Pass
            Comment: "Flujo para usuario registrado sin Tag (Caso B)"
            Result: "Procesando usuario registrado"
            Next: CalculateCharge
          ProcessUnregisteredUser:
            Type: Pass
            Comment: "Flujo para usuario no registrado (Caso A)"
            Result: "Procesando usuario no registrado"
            Next: CalculateCharge
          CalculateCharge:
            Type: Task
            Resource: !GetAtt CalculateChargeFunction.Arn
            Comment: "Calcula monto según tipo de usuario (aplica tarifas diferentes)"
            Next: PersistTransaction
            Catch:
              - ErrorEquals:
                  - States.ALL
                ResultPath: "$.error"
                Next: HandleError
          PersistTransaction:
            Type: Task
            Resource: !GetAtt PersistTransactionFunction.Arn
            Comment: "Guarda transacción e invoice en DynamoDB"
            Next: SendNotification
            Catch:
              - ErrorEquals:
                  - States.ALL
                ResultPath: "$.error"
                Next: HandleError
          SendNotification:
            Type: Task
            Resource: !GetAtt SendNotificationFunction.Arn
            Comment: "Envía notificación vía SNS"
            End: true
            Catch:
              - ErrorEquals:
                  - States.ALL
                ResultPath: "$.error"
                Next: HandleError
          HandleError:
            Type: Fail
            Error: "ProcessingFailed"
            Cause: "Error processing toll transaction"
      Role: !GetAtt StepFunctionsExecutionRole.Arn
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StepFunctionsLogGroup.Arn

  StepFunctionsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/stepfunctions/${ProjectName}-process-toll-${StageName}"
      RetentionInDays: 14

  #### DynamoDB ####
  UsersVehicles:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: placa
          AttributeType: S
      KeySchema:
        - AttributeName: placa
          KeyType: HASH
      TableName: !Sub "UsersVehicles-${StageName}"

  Tags:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tag_id
          AttributeType: S
      KeySchema:
        - AttributeName: tag_id
          KeyType: HASH
      TableName: !Sub "Tags-${StageName}"

  TollsCatalog:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: peaje_id
          AttributeType: S
      KeySchema:
        - AttributeName: peaje_id
          KeyType: HASH
      TableName: !Sub "TollsCatalog-${StageName}"

  Transactions:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: placa
          AttributeType: S
        - AttributeName: ts
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
        - AttributeName: event_id
          AttributeType: S
      KeySchema:
        - AttributeName: placa
          KeyType: HASH
        - AttributeName: ts
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: by_event
          KeySchema:
            - AttributeName: event_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: placa-timestamp-index
          KeySchema:
            - AttributeName: placa
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TableName: !Sub "Transactions-${StageName}"

  Invoices:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: placa
          AttributeType: S
        - AttributeName: invoice_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: placa
          KeyType: HASH
        - AttributeName: invoice_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: placa-created-index
          KeySchema:
            - AttributeName: placa
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TableName: !Sub "Invoices-${StageName}"

  #### SNS ####
  NotificationsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "Notifications-${StageName}"

  #### Lambda Functions ####
  
  IngestWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-ingest-webhook-${StageName}"
      CodeUri: ../src/functions/ingest_webhook
      Handler: app.lambda_handler
      Description: Recibe eventos HTTP de peajes y publica en EventBridge
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Tags
        - DynamoDBReadPolicy:
            TableName: !Ref TollsCatalog
        - Statement:
            - Effect: Allow
              Action:
                - events:PutEvents
              Resource: !GetAtt GuatePassBus.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /webhook/toll
            Method: post

  ReadHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-read-history-${StageName}"
      CodeUri: ../src/functions/read_history
      Handler: app.lambda_handler
      Description: Consulta historial de pagos e invoices por placa
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Transactions
        - DynamoDBReadPolicy:
            TableName: !Ref Invoices
      Events:
        ApiPaymentEvent:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /history/payments/{placa}
            Method: get
        ApiInvoiceEvent:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            Path: /history/invoices/{placa}
            Method: get

  SeedCsvFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-seed-csv-${StageName}"
      CodeUri: ../src/functions/seed_csv
      Handler: app.lambda_handler
      Description: Pobla las tablas DynamoDB con datos iniciales
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersVehicles
        - DynamoDBCrudPolicy:
            TableName: !Ref Tags
        - DynamoDBCrudPolicy:
            TableName: !Ref TollsCatalog

  ValidateTransactionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-validate-transaction-${StageName}"
      CodeUri: ../src/functions/validate_transaction
      Handler: app.lambda_handler
      Description: Valida peaje, determina tipo de usuario y valida tag
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersVehicles
        - DynamoDBReadPolicy:
            TableName: !Ref Tags
        - DynamoDBReadPolicy:
            TableName: !Ref TollsCatalog

  CalculateChargeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-calculate-charge-${StageName}"
      CodeUri: ../src/functions/calculate_charge
      Handler: app.lambda_handler
      Description: Calcula el monto a cobrar según tipo de usuario y tarifas

  PersistTransactionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-persist-transaction-${StageName}"
      CodeUri: ../src/functions/persist_transaction
      Handler: app.lambda_handler
      Description: Persiste transacción e invoice en DynamoDB
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Transactions
        - DynamoDBCrudPolicy:
            TableName: !Ref Invoices

  SendNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-send-notification-${StageName}"
      CodeUri: ../src/functions/send_notification
      Handler: app.lambda_handler
      Description: Envía notificación del resultado de la transacción vía SNS
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !Ref NotificationsTopic

  #### IAM Roles ####
  
  EventBridgeStepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeStepFunctions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !GetAtt ProcessTollStateMachine.Arn

  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambdaFunctions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt ValidateTransactionFunction.Arn
                  - !GetAtt CalculateChargeFunction.Arn
                  - !GetAtt PersistTransactionFunction.Arn
                  - !GetAtt SendNotificationFunction.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                Resource: "*"

Outputs:
  ApiUrl:
    Description: URL base del API (stage actual)
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
  WebhookEndpoint:
    Description: Endpoint para ingesta de eventos de peaje
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/webhook/toll"
  PaymentsHistoryEndpoint:
    Description: Endpoint para consultar historial de pagos
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/history/payments/{placa}"
  InvoicesHistoryEndpoint:
    Description: Endpoint para consultar historial de invoices
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/history/invoices/{placa}"
  EventBusName:
    Description: Nombre del EventBridge Bus
    Value: !Ref GuatePassBus
  StateMachineArn:
    Description: ARN de la State Machine
    Value: !GetAtt ProcessTollStateMachine.Arn
  StateMachineName:
    Description: Nombre de la State Machine
    Value: !Sub "${ProjectName}-process-toll-${StageName}"
  SnsTopicArn:
    Description: ARN del SNS Topic para notificaciones
    Value: !Ref NotificationsTopic
  Tables:
    Description: Tablas DynamoDB creadas
    Value: !Sub |
      UsersVehicles=${UsersVehicles}
      Tags=${Tags}
      TollsCatalog=${TollsCatalog}
      Transactions=${Transactions}
      Invoices=${Invoices}
