AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GuatePass - Sistema de Cobro Automatizado de Peajes (Serverless Event-Driven)

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.13
    Environment:
      Variables:
        USERS_TABLE: !Ref UsersTable
        TAGS_TABLE: !Ref TagsTable
        TRANSACTIONS_TABLE: !Ref TransactionsTable
        INVOICES_TABLE: !Ref InvoicesTable
        TOLLS_CATALOG_TABLE: !Ref TollsCatalogTable
        EVENT_BUS_NAME: !Ref TollEventBus
        STATE_MACHINE_ARN: !Ref ProcessTollStateMachine
        SNS_TOPIC_ARN: !Ref NotificationTopic

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Environment name (dev, staging, prod)
  ProjectName:
    Type: String
    Default: guatepass
    Description: Project name prefix for resources
  StageName:
    Type: String
    Default: dev
    Description: API Gateway stage name (ej. dev, staging, prod)

Resources:
  GuatePassApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub '${ProjectName}-api-${Environment}'
      StageName: !Ref StageName
      EndpointConfiguration: REGIONAL
      Cors: "'*'"

  # ============================================
  # API GATEWAY
  # ============================================

  # ============================================
  # DYNAMODB TABLES
  # ============================================
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-users-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: placa
          AttributeType: S
      KeySchema:
        - AttributeName: placa
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  TagsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-tags-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: tag_id
          AttributeType: S
      KeySchema:
        - AttributeName: tag_id
          KeyType: HASH
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-transactions-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S
        - AttributeName: placa
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: placa-timestamp-index
          KeySchema:
            - AttributeName: placa
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  InvoicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-invoices-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: invoice_id
          AttributeType: S
        - AttributeName: placa
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: invoice_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: placa-created-index
          KeySchema:
            - AttributeName: placa
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  TollsCatalogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-tolls-catalog-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: peaje_id
          AttributeType: S
      KeySchema:
        - AttributeName: peaje_id
          KeyType: HASH
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # ============================================
  # EVENTBRIDGE
  # ============================================
  TollEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub '${ProjectName}-eventbus-${Environment}'

  TollEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref TollEventBus
      EventPattern:
        source:
          - guatepass.toll
        detail-type:
          - Toll Transaction Event
      State: ENABLED
      Targets:
        - Arn: !GetAtt ProcessTollStateMachine.Arn
          Id: ProcessTollTarget
          RoleArn: !GetAtt EventBridgeStepFunctionsRole.Arn
          InputTransformer:
            InputPathsMap:
              detail: "$.detail"
            InputTemplate: "<detail>"

  # ============================================
  # STEP FUNCTIONS
  # ============================================
  ProcessTollStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub '${ProjectName}-process-toll-${Environment}'
      DefinitionString: !Sub
        - |
          {
            "Comment": "Procesa transacción de peaje",
            "StartAt": "ValidateTransaction",
            "States": {
              "ValidateTransaction": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ValidateTransactionFunctionName}",
                "Next": "CalculateCharge",
                "Catch": [{
                  "ErrorEquals": ["States.ALL"],
                  "ResultPath": "$.error",
                  "Next": "HandleError"
                }]
              },
              "CalculateCharge": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${CalculateChargeFunctionName}",
                "Next": "PersistTransaction",
                "Catch": [{
                  "ErrorEquals": ["States.ALL"],
                  "ResultPath": "$.error",
                  "Next": "HandleError"
                }]
              },
              "PersistTransaction": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${PersistTransactionFunctionName}",
                "Next": "SendNotification",
                "Catch": [{
                  "ErrorEquals": ["States.ALL"],
                  "ResultPath": "$.error",
                  "Next": "HandleError"
                }]
              },
              "SendNotification": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${SendNotificationFunctionName}",
                "End": true,
                "Catch": [{
                  "ErrorEquals": ["States.ALL"],
                  "ResultPath": "$.error",
                  "Next": "HandleError"
                }]
              },
              "HandleError": {
                "Type": "Fail",
                "Error": "ProcessingFailed",
                "Cause": "Error processing toll transaction"
              }
            }
          }
        - ValidateTransactionFunctionName: !Sub '${ProjectName}-validate-transaction-${Environment}'
          CalculateChargeFunctionName: !Sub '${ProjectName}-calculate-charge-${Environment}'
          PersistTransactionFunctionName: !Sub '${ProjectName}-persist-transaction-${Environment}'
          SendNotificationFunctionName: !Sub '${ProjectName}-send-notification-${Environment}'
      RoleArn: !GetAtt StepFunctionsExecutionRole.Arn
      LoggingConfiguration:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StepFunctionsLogGroup.Arn

  StepFunctionsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/stepfunctions/${ProjectName}-process-toll-${Environment}'
      RetentionInDays: 14

  # ============================================
  # SNS TOPIC
  # ============================================
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-notifications-${Environment}'
      DisplayName: GuatePass Notifications

  # ============================================
  # LAMBDA FUNCTIONS
  # ============================================
  IngestWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-ingest-webhook-${Environment}'
      CodeUri: ../src/functions/ingest_webhook
      Handler: app.lambda_handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /webhook/toll
            Method: post
            RestApiId: !Ref GuatePassApi
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TagsTable
        - DynamoDBReadPolicy:
            TableName: !Ref TollsCatalogTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - events:PutEvents
              Resource: !GetAtt TollEventBus.Arn
      Environment:
        Variables:
          EVENT_BUS_NAME: !Ref TollEventBus

  ReadHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-read-history-${Environment}'
      CodeUri: ../src/functions/read_history
      Handler: app.lambda_handler
      Events:
        ApiPaymentEvent:
          Type: Api
          Properties:
            Path: /history/payments/{placa}
            Method: get
            RestApiId: !Ref GuatePassApi
        ApiInvoiceEvent:
          Type: Api
          Properties:
            Path: /history/invoices/{placa}
            Method: get
            RestApiId: !Ref GuatePassApi
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TransactionsTable
        - DynamoDBReadPolicy:
            TableName: !Ref InvoicesTable

  SeedCsvFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-seed-csv-${Environment}'
      CodeUri: ../src/functions/seed_csv
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TagsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref TollsCatalogTable

  ValidateTransactionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-validate-transaction-${Environment}'
      CodeUri: ../src/functions/validate_transaction
      Handler: app.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
        - DynamoDBReadPolicy:
            TableName: !Ref TagsTable
        - DynamoDBReadPolicy:
            TableName: !Ref TollsCatalogTable

  CalculateChargeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-calculate-charge-${Environment}'
      CodeUri: ../src/functions/calculate_charge
      Handler: app.lambda_handler

  PersistTransactionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-persist-transaction-${Environment}'
      CodeUri: ../src/functions/persist_transaction
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TransactionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref InvoicesTable

  SendNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-send-notification-${Environment}'
      CodeUri: ../src/functions/send_notification
      Handler: app.lambda_handler
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !Ref NotificationTopic

  # ============================================
  # IAM ROLES
  # ============================================
  EventBridgeStepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeStepFunctions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Ref ProcessTollStateMachine

  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambdaFunctions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ProjectName}-*-${Environment}'
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:DescribeLogGroups
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:CreateLogGroup
                  - logs:DescribeLogStreams
                  - logs:PutLogEvents
                Resource: "*"

Outputs:
  ApiGatewayUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${GuatePassApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}'
    Export:
      Name: !Sub '${ProjectName}-api-url-${Environment}'
  
  IngestWebhookUrl:
    Description: Webhook endpoint for toll ingestion
    Value: !Sub 'https://${GuatePassApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/webhook/toll'
  
  StateMachineArn:
    Description: Step Functions State Machine ARN
    Value: !GetAtt ProcessTollStateMachine.Arn
    Export:
      Name: !Sub '${ProjectName}-statemachine-arn-${Environment}'
  
  EventBusName:
    Description: EventBridge Event Bus Name
    Value: !Ref TollEventBus
    Export:
      Name: !Sub '${ProjectName}-eventbus-name-${Environment}'
